theme: jekyll-theme-cayman
title: Welcome to Marco's GitHub website
description: I will be putting my updates on current projects here
# Rotation Projects
## Rock Paper Scissors
[RoShamBo](https://repl.it/@MarcoTortilla/GrizzledFlamboyantSystemsanalysis) 
